version: '3'
services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_DB: CFSP-DB
      POSTGRES_USER: CFSP-USER
      POSTGRES_PASSWORD: CFSP-PASSWORD # Password for PostgreSQL
    networks:
      - cloud-network
    # descomente se quiser acessar o banco de dados externamente
    #ports:
    #  - 5432:5432
    volumes:
      - postgres-data:/var/lib/postgresql/data

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    environment:
      # configuration for backend
      API_PORT: 3000
      JWT_SECRET: ${JWT_SECRET}
      # configuration for postgres
      POSTGRES_PORT: 5432
      POSTGRES_HOST: postgres
      POSTGRES_DB_NAME: CFSP-DB
      POSTGRES_USER: CFSP-USER
      POSTGRES_PASSWORD: CFSP-PASSWORD # Password for PostgreSQL

      # configuration for gcs
      GCS_BUCKET_NAME: ${GCS_BUCKET_NAME}
      GCS_PROJECT_ID: ${GCS_PROJECT_ID}
    depends_on:
        - postgres
    ports:
      - 3000:3000
    networks:
      - cloud-network
    volumes:
      - backend-data:/app/

  nginx:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    environment:
      API_PROTOCOL: https
      API_IP: ${public ip api}
      API_PORT: 3000
    depends_on:
      - backend
    ports:
      - 80:80
      - 443:443
    networks:
      - cloud-network


networks:
  cloud-network:

volumes:
  backend-data:
  postgres-data:
